spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TelegramFramework?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      connection-init-sql: set names 'utf8mb4'
  jpa:
    hibernate:
      ddl-auto: update
telegram-bot:
  token:
  connect-way: updateListener
  proxy:
    type: SOCKS
    address: 127.0.0.1
    port: 1080
coolq:
  proxy:
      type: SOCKS
      address: 127.0.0.1
      port: 1080
  access-token:
  web-socket-address: 127.0.0.1
  web-socket-port: 1234

